### ISSUE TITLE
Keep a simple major.minor version for the spec, plus a revision

### ISSUE THREAD

**Issue by llemeurfr** [readium/lcp-specs#39]
I disagree with the renaming of the specification, by the addition of a patch number **in the title**.

This makes users worrying about the stability of the specification (and therefore their implementation) where the evolution is only on the wording of the spec (and implementation is untouched).  

I therefore advise to revert to a "Revision X" label on the top of the text, before the links to the previous version (or revision).

**Comment by HadrienGardeur** [comment]
I think these are valid points but there are related questions:

- how do we name files for these revisions (aside from the latest one)? Since this is a Markdown repo, we can't rely entirely on routes to hide things.
- do we provide linking between revisions (top links in the document)?

**Comment by HadrienGardeur** [comment]
My own take on these questions:

- we can indeed go back to revisions
- file names can remain as-is
- we should provide linking between versions but not revisions, but all versions/revisions should point to the latest one

**Comment by llemeurfr** [comment]
> we should provide linking between versions but not revisions

not sure I understand. do you mean we should not keep snapshots of previous revisions (i.e. evolution of wording) and therefore not link a revision to the previous one?

**Comment by HadrienGardeur** [comment]
You can see an example now for LCP:

- [latest version](https://readium.org/lcp-specs/releases/lcp/latest.html)
- [snapshot of revision 2](https://readium.org/lcp-specs/releases/lcp/lcp-1-0-2)

As mentioned above:

- title is the same
- the revision is clearly indicated
- all documents point to the latest version/revision
- none of them point to a previous version since there's no LCP 0.9
- none of them point to a next version either since LCP 1.1 isn't out yet

**Comment by llemeurfr** [comment]
I can leave with no link back to the previous revision, which has pros and cons.
pros = clear display of the path of evolution
cons = insecurity for the reader about what is a revision of the wording vs a real evolution.
