### ISSUE TITLE
Return callback

### ISSUE THREAD

**Issue by treping** [readium/lcp-specs#44]
I try to handle call back when a book is return with thorium
the return work
but the call back is never call

   "links":[
	{
         "rel":"return",
         "href":"https://something.com/api_dev/licenses.aspx?test=1",
         "type":"application/vnd.readium.license.status.v1.0+json",
         "length":null,
         "hash":null,
         "title":null,
         "templated":false
      }
   ],

LCP should call this url https://something.com/api_dev/licenses.aspx?test=1 when the book is return right ?
it will be a GET our a PUT ?

**Comment by danielweck** [comment]
Hello Jason, last time I checked (quite recently), Thorium's LCP `return` function worked.
The HTTP request uses a `PUT` method:
https://github.com/readium/r2-lcp-js/blob/0b4533e496d9078566369b28ddf6cf05be40d3c2/src/lsd/return.ts#L174-L190
The URL is usually templated:
https://github.com/readium/r2-lcp-js/blob/0b4533e496d9078566369b28ddf6cf05be40d3c2/src/lsd/return.ts#L81-L89

**Comment by danielweck** [comment]
Feel free to post an issue in Thorium's GitHub repository, if you think the implementation is incorrect:
https://github.com/edrlab/thorium-reader/issues

**Comment by danielweck** [comment]
Specification: https://readium.org/lcp-specs/releases/lsd/latest#34-returning-a-publication

**Comment by treping** [comment]
the return work. it the call back that doesn't work,  
the LCP Server should call the return url provide during creation of the license?

"rel":"return",
"href":"https://something.com/api_dev/licenses.aspx?test=1",

https://something.com/api_dev/licenses.aspx?test=1 : is never call so we are not aware that the book is return

**Comment by treping** [comment]
> Feel free to post an issue in Thorium's GitHub repository, if you think the implementation is incorrect:
> https://github.com/edrlab/thorium-reader/issues



> Feel free to post an issue in Thorium's GitHub repository, if you think the implementation is incorrect:
> https://github.com/edrlab/thorium-reader/issues

LCP or Thorium will make the callback ? the one provide here
{
  "links": [
    {
      "rel": "return",
      **"href": "https://example.org/license/aaa-bbbb-ccc/return{?id,name}",**
      "type": "application/vnd.readium.license.status.v1.0+json",
      "templated": true
    }
  ]
}

**Comment by HadrienGardeur** [comment]
If you're talking about the open-source server, this is the wrong repo for that.

**Comment by danielweck** [comment]
You seem to be conflating the `return` LSD interaction (as documented here https://readium.org/lcp-specs/releases/lsd/latest#34-returning-a-publication ) with some sort of automatic "callback" (I am not entirely sure what you mean ... are you confusing this with JSONP?).

The optionally-provided LSD `return` link is a "command" which a LCP client (like Thorium) invokes as a `PUT` HTTP request. The server behind the `return` URL endpoint sends a response with success or error codes, as described in the specification. The server is responsible for actually performing the requested license `return` (either directly or via delegation to another service in the LCP/LSD "backend" infrastructure). The client is responsible for displaying the result so that the end-user is aware of the outcome (e.g. successful `return`, in which case the publication cannot be read anymore)

If you believe there is a bug in the Go server open source implementation, feel free to file an issue: https://github.com/readium/readium-lcp-server/issues
