### ISSUE TITLE
Certificate expiration: what will happen ?

### ISSUE THREAD

**Issue by dblugeon** [readium/lcp-specs#50]
Hello,
I have question about certificate expiration.
in the [edrlab faq](https://www.edrlab.org/readium-lcp/faq/), we found this statement:

> Users can freely transfer a publication from one device to another. They can expect being able to continue reading it year after year after download, even if their bookseller closes its operation, thanks to the offline capabilities of the solution.

In the spec, a lcp book has a provider certificate and a root certificate used to validate the license. In the case when the bookseller is closed, what happen when the certificate (root or provider) expires ? Logically, the user looses access to his books, am I right?

**Comment by llemeurfr** [comment]
Sorry for the delay, 

No the user does not loose access to his ebooks if the bookseller closes and his certificate expires. This is because in https://readium.org/lcp-specs/releases/lcp/latest#55-validating-the-certificate-and-signature it is clearly stated: 

"The Reading System must check that the Certificate was not expired when the License Document was last updated."

"was last updated" -> at a time the bookseller was still active. 

The system does not check the expiration of the Certificate vs the current date, but vs the date the license WAS generated or updated (in case of renew or return).

**Comment by dblugeon** [comment]
Thank you for your explanation and précisions.
