### ISSUE TITLE
identification of content document is unclear; content substitution attacks

### ISSUE THREAD

**Issue by eshellman** [readium/lcp-specs#7]
I'm not sure that the spec makes clear how the protected content document is to be identified.

In section 3.5 of the lcp spec suggests an optional hash of the publication be included in the links section of the license document, and in section 7.2 it is specified that the reader "should" verify the hash of the protected publication. It's not clear what should be hashed if the protected document already includes the license document.

Either way, without a hash of the protected document, it looks to me as though the reader application  is vulnerable to content substitution attacks. The license validates, a valid user key is used to decrypt the content key, and the content key decrypts the content. But I don't see how the content/ content key is checked to verify that it is the resource named in the license (absent the hash).

**Comment by HadrienGardeur** [comment]
To substitute content protected by an LCP license you would need to know the AES key used to encrypt the original content, and also have access to a valid private key in order to sign the document.
If a private key is compromised, the certificate associated to it would usually be revoked and that info transmitted using the CRL.

Most of the time, the LCP license will be provided separately from the publication:

- the user gets an .lcpl document
- this document is opened in a compatible app where the license is verified and the content downloaded
- if the link to the publication contains a hash, it is verified by the reading app

**Comment by danielweck** [comment]
The 'link' property with the 'publication' rel in the LCPL file references an encrypted EPUB without 'META-INF/license.lcpl', so the hash is always the same.

**Comment by eshellman** [comment]
@HadrienGardeur without the hash, there's not a way for the reader app to be sure that a valid license and a valid user key are in fact associated with the content (and encrypted content key) that is present in the epub. Or have I misunderstood?

Also, if a user obtains a valid license without a hash for example from one provider, can't that license be used to decrypt any encrypted content key, for example from other providers? If not please improve the explanation.

**Comment by HadrienGardeur** [comment]
Sorry @eshellman but I'm starting to wonder if you've really read the spec after that question...

Of course one license can't be used to decrypt another publication:

- for each publication, a unique content key is used
- each content key is then  encrypted using a User Key

If you tried to use a license on a different publication, it would just completely fail to decrypt since you'd have the wrong content key.

That's why I already said that to forge a license content document you'd need to have access to both a valid certificate and it's private key, but also to the shared crypto materials in the ecosystem.
I'm not saying that this can't happen, but that's a very serious breach and even in that case it would be possible to revoke the stolen certificate.

**Comment by eshellman** [comment]
My understanding, on having studied the spec is:
1. the encrypted content key is delivered along with the content package. The content key, not the content, is encrypted using the user key.
2. if presented with any valid license, the reader app will use the user key to decrypt the content key. It will only check the identity of the content if the license contains a hash. Other than that, its only the fact that the content key must be encrypted with a user key generated from the same pass phrase that restricts the decryption to the instant document.
3. so, given a valid license without hash, a reader app can be tricked into decrypting any document key, and thus the accompanying document, whose content key has been decrypted with the same pass phrase. (The license is locked to the user key using the "key check".)

Please respect efforts of readers like me to understand the spec as written.

**Comment by HadrienGardeur** [comment]
1. That part is almost correct, most of the time the license will be delivered first and this will trigger the download of the publication.
2. Except in the case of the interoperable ecosystem where a valid certificate, a certification revocation list and additional crypto materials are all used to validate access to the document.
3. In this scenario, an attacker has replaced the publication that is linked to? 
I don't see what you mean by "a reader app can be tricked into decrypting any document key". You can't use the same license with two different publications as long as these two publications use different content keys (which is always the case).

**Comment by eshellman** [comment]
1. ...and easy to spoof a publication download.
2. "additional crypto" doesn't lock the license to the content key, only to the user key, is this correct?
3. ...but the content key is delivered (encrypted) with the content, and only the user key and additional crypto are used to unlock the content key.

I'm thinking about the context of a library borrow. The license delivered with the borrowed book includes an expiration date. If the user swaps in a valid license without hash from a purchased book (purchased with the same pass phrase), then the expiration will be negated. License swapping is a trivial script.

**Comment by jpbougie** [comment]
As Hadrien said before, the content key is required to be unique (or unlikely enough to be repeating, by using a cryptographic random number generator for example) for each encrypted EPUB. Trying to use a content key with another file will simply result in a garbled output, just as you would get if you directly tried to decrypt a file by inputting a random content key. 

There is of course the possibility of a proxy, evil or not, sending a bad file, which is why, as you pointed out, we should require either a TLS transfer and/or a digest of the file contents to insure its integrity, but the end result would just be an error while opening the file in a reading system.

For the borrow use case, I don't understand the issue, could you explain it? If a user got both a temporary license from his public library and a permanent license from a bookstore for the same EPUB, a license swap would produce exactly the same output as downloading the file anew. Again, this will not work if you swap the license with another encrypted EPUB, as the Content key will be different.

**Comment by eshellman** [comment]
@jpbougie if there is a digest (hash) of the file contents in the license file, there is no possibility to use the license file for a different content. But this is optional is the spec, so license files without a file digest can exist. 

The fact that each document has a different content key is not relevant if the content key can be decrypted using the same user key used for other documents.

Making the digest a required element of the license document is a straightforward way of blocking license swapping.

Note that TLS transfer of the file contents, while it is important, is not a useful protection against license swapping if there is access to the stored file on the device.

**Comment by jpbougie** [comment]
I fail to see how that will result in anything but a corrupt/garbled output.

For example, let's say we have an EPUB `A` that is encrypted using `content-key-A`, and an EPUB `B`, encrypted using `content-key-B`. Both Content Keys are different binary values of 256 bits obtained through the use of a cryptographically secure pseudorandom number generator (i.e. /dev/urandom in general).

We then emit 2 licenses `license-A` and `license-B`, using the passphrase `passphrase`. In each License file, we have a field `encryption.content_key.encrypted_value`, which are is encrypted using `passphrase`, giving `encrypted-value-A` and `encrypted-value-B`.

If we successfully decrypt `encrypted-value-A`, we get `content-key-A`. Equivalently, we get `content-key-B` from `encrypted-value-B`. Using the corresponding content key to an encrypted EPUB will result in the cleartext version of the content.

If we try to apply `content-key-A` on any file in EPUB `B`, we'll just get corrupted data. The AES symmetric cipher guarantees that only the proper key will be be able to restore the original content.

**Comment by eshellman** [comment]
OK, now I understand! The encrypted content key is also contained in the signed license. I was confused by the "..."  and "encryption/content_key" notations and thought that the encrypted content key would be delivered in the META-INF/encryption.xml file. My sincere thanks to @jpbougie and @HadrienGardeur for trying to help me understand, and my apologies for misunderstanding the spec.
